local M = {}

local colors = require("soft.palette")

M.setup = function()
	return {
		Normal = { link = "Normal" },
		NormalNC = { link = "Normal" },
		NormalFloat = { link = "Normal" },
		Comment = { fg = colors.textFaded, italic = true },
		Constant = { fg = colors.purpleDarkest },
		String = { fg = colors.blue },
		Character = { link = "String" },
		Number = { fg = colors.blue },
		Boolean = { fg = colors.hotPink },
		Float = { link = "Number" },
		FloatBorder = { link = "Normal" },
		Operator = { fg = colors.salmon },
		Keyword = { fg = colors.purpleDarkest, italic = true, cterm = { italic = true }, force = true },
		Keywords = { link = "Keyword" },
		Variable = { fg = colors.purpleDefault },
		Identifier = { fg = colors.blue },
		Function = { fg = colors.orange },
		Statement = { link = "Keyword" },
		Conditional = { fg = colors.blue },
		Repeat = { fg = colors.blue },
		Label = { fg = colors.blue },
		Exception = { fg = colors.violet },
		PreProc = { fg = colors.yellow },
		Include = { fg = colors.hotPink },
		Define = { fg = colors.violet },
		Title = { fg = colors.blue },
		Macro = { fg = colors.hotPink },
		PreCondit = { fg = colors.blue },
		Type = { fg = colors.greenFaded },
		Class = { fg = colors.green },
		StorageClass = { fg = colors.blue },
		Structure = { fg = colors.yellow },
		TypeDef = { fg = colors.yellow },
		Special = { fg = colors.blue, italic = true },
		SpecialComment = { link = "Comment" },
		Error = { fg = colors.red },
		Todo = { fg = colors.violet, bold = false, italic = true },
		Underlined = { fg = colors.blue, underline = true },

		Cursor = {
			fg = colors.background,
			bg = colors.salmon,
		},
		CursorLineNr = { fg = colors.textEmphasis, bold = true },

		SignColumn = { bg = colors.background },

		Conceal = { fg = colors.textFaded },
		CursorColumn = { fg = colors.background, bg = colors.salmon },
		CursorLine = { bg = colors.background },
		ColorColumn = { bg = colors.purpleLight },

		StatusLine = { fg = colors.purpleDefault, bg = colors.purpleLight },
		StatusLineNC = { fg = colors.textEmphasis, bg = colors.purpleDarkest },
		StatusLineTerm = { fg = colors.purpleDefault, bg = colors.purpleLight },
		StatusLineTermNC = { fg = colors.textEmphasis, bg = colors.purpleDarkest },

		Directory = { fg = colors.green },
		DiffAdd = { fg = colors.greenFaded },
		DiffChange = { fg = colors.yellow },
		DiffDelete = { fg = colors.red },
		DiffText = { fg = colors.textFaded },

		ErrorMsg = { fg = colors.red },
		VertSplit = { fg = colors.purpleDefault },
		WinSeparator = { fg = colors.purpleDefault },
		Folded = { fg = colors.textFaded },
		FoldColumn = {},
		Search = { fg = colors.purpleDarkest, bg = colors.purpleLight },
		IncSearch = { fg = colors.redDarker, bg = colors.salmon },
		LineNr = { fg = colors.textFaded },
		MatchParen = { underline = true },
		NonText = { fg = colors.nontext, bg = colors.background },
		Pmenu = { fg = colors.purpleDarkest, bg = colors.purpleLight },
		PmenuSel = { fg = colors.purpleDarkest, blend = 0, bg = colors.purpleDefault },
		PmenuSbar = { fg = colors.debug1, bg = colors.debug2 },
		PmenuThumb = { fg = colors.debug1, bg = colors.debug2 },

		Question = { fg = colors.debug2 },
		QuickFixLine = { fg = colors.purpleDefault, bg = colors.yellow },
		SpecialKey = { fg = colors.red, bg = colors.background },

		SpellBad = { fg = colors.red, underline = true },
		SpellCap = { fg = colors.yellow },
		SpellLocal = { fg = colors.yellow },
		SpellRare = { fg = colors.yellow },

		Terminal = { link = "Normal" },
		Visual = { bg = colors.background },
		VisualNOS = { fg = colors.salmon },
		WarningMsg = { fg = colors.yellow },
		WildMenu = { link = "Normal" },

		-- tabline styles
		TabLine = { fg = colors.purpleLight, bg = colors.background, italic = true },
		TabLineSel = { fg = colors.purpleDarkest, bg = colors.background, bold = false },
		TabLineFill = { fg = colors.purpleLight, bg = colors.background },

		-- which-key
		WhichKey = { fg = colors.purpleDarkest },
		WhichKeyBorder = { fg = colors.purpleDarkest, bg = colors.background },
		WhichKeyNormal = { link = "Normal" },

		-- telescope
		TelescopeBorder = { link = "Normal" },

		-- mini.indentscope
		MiniIndentscopeSymbol = { fg = colors.textFaded },

		-- trouble
		TroubleNormal = { link = "Normal" },
		TroubleText = { link = "Normal" },
		TroubleNormalNC = { link = "Normal" },

		-- lazy
		LazyBold = { fg = colors.purpleDefault, bg = colors.background, bold = false },
		LazyH2 = { fg = colors.purpleDefault, bg = colors.background, bold = false },

		-- TreeSitter
		["@error"] = { link = "Error" },
		["@punctuation.delimiter"] = { fg = colors.purpleDefault },
		["@punctuation.bracket"] = { fg = colors.purpleDefault },
		["@punctuation.special"] = { fg = colors.blue },

		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Constant" },
		["@symbol"] = { fg = colors.violet },

		["@constant.macro"] = { link = "Constant" },
		["@string.regex"] = { fg = colors.red },
		["@string"] = { fg = colors.string },
		["@string.escape"] = { fg = colors.blue },
		["@character"] = { link = "Number" },
		["@number"] = { link = "Number" },
		["@boolean"] = { fg = colors.yellow },
		["@float"] = { link = "Number" },
		["@annotation"] = { fg = colors.yellow },
		["@attribute"] = { fg = colors.blue },
		["@namespace"] = { link = "Number" },

		["@function.builtin"] = { link = "Function", bold = false },
		["@function"] = { link = "Function", bold = false },
		["@function.macro"] = { link = "Function" },
		["@parameter"] = { link = "Number" },
		["@parameter.reference"] = { link = "Number" },
		["@method"] = { link = "Number" },
		["@field"] = { link = "Number" },
		["@property"] = { link = "Type" },
		["@constructor"] = { fg = colors.blue },

		["@conditional"] = { fg = colors.blue },
		["@repeat"] = { fg = colors.blue },
		["@label"] = { fg = colors.blue },

		["@keyword"] = { link = "Keyword" },
		["@keyword.function"] = { link = "Function" },
		["@keyword.function.ruby"] = { link = "Function" },
		["@keyword.operator"] = { fg = colors.blue },
		["@operator"] = { fg = colors.blue },
		["@exception"] = { fg = colors.violet },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { link = "Type", italic = true },
		["@type.qualifier"] = { link = "Type" },
		["@structure"] = { fg = colors.violet },
		["@include"] = { fg = colors.blue },

		["@variable"] = { link = "Variable" },
		["@variable.builtin"] = { link = "Variable" },

		["@text"] = { link = "Normal" },
		["@text.strong"] = { fg = colors.purpleDefault, bold = true }, -- bold
		["@text.emphasis"] = { fg = colors.red, italic = true }, -- italic
		["@text.underline"] = { fg = colors.purpleDefault, underline = true },
		["@text.title"] = { fg = colors.purpleDarkest, bold = true }, -- title
		["@text.literal"] = { link = "Number" }, -- inline code
		["@text.uri"] = { fg = colors.blue, italic = true }, -- urls
		["@text.reference"] = { fg = colors.green, bold = true },

		["@tag"] = { fg = colors.blue },
		["@tag.attribute"] = { link = "Number" },
		["@tag.delimiter"] = { fg = colors.blue },

		-- Semantic
		["@class"] = { link = "Class" },
		["@struct"] = { fg = colors.blue },
		["@enum"] = { fg = colors.blue },
		["@enumMember"] = { fg = colors.violet },
		["@event"] = { fg = colors.blue },
		["@interface"] = { fg = colors.blue },
		["@modifier"] = { fg = colors.blue },
		["@regexp"] = { fg = colors.yellow },
		["@typeParameter"] = { fg = colors.blue },
		["@decorator"] = { fg = colors.blue },

		-- LSP Semantic (0.9+)
		["@lsp.type.class"] = { link = "Class" },
		["@lsp.type.enum"] = { fg = colors.blue },
		["@lsp.type.decorator"] = { link = "Number" },
		["@lsp.type.enumMember"] = { fg = colors.violet },
		["@lsp.type.function"] = { link = "Number" },
		["@lsp.type.interface"] = { fg = colors.yellow },
		["@lsp.type.macro"] = { fg = colors.blue },
		["@lsp.type.method"] = { link = "Number" },
		["@lsp.type.namespace"] = { link = "Number" },
		["@lsp.type.parameter"] = { link = "Number" },
		["@lsp.type.property"] = { fg = colors.violet },
		["@lsp.type.struct"] = { fg = colors.blue },
		["@lsp.type.type"] = { fg = colors.yellow },
		["@lsp.type.variable"] = { fg = colors.purpleDefault },

		-- HTML
		htmlArg = { fg = colors.blue },
		htmlBold = { bold = true },
		htmlEndTag = { fg = colors.blue },
		htmlH1 = { fg = colors.blue },
		htmlH2 = { fg = colors.blue },
		htmlH3 = { fg = colors.blue },
		htmlH4 = { fg = colors.blue },
		htmlH5 = { fg = colors.blue },
		htmlH6 = { fg = colors.blue },
		htmlItalic = { fg = colors.violet, italic = true },
		htmlLink = { fg = colors.violet, underline = true },
		htmlSpecialChar = { fg = colors.yellow },
		htmlSpecialTagName = { fg = colors.blue },
		htmlTag = { fg = colors.blue },
		htmlTagN = { fg = colors.blue },
		htmlTagName = { fg = colors.blue },
		htmlTitle = { fg = colors.white },

		-- Markdown
		markdownBlockquote = { fg = colors.yellow, italic = true },
		markdownBold = { fg = colors.orange, bold = true },
		markdownCode = { fg = colors.red, bg = colors.backgroundDarkest },
		markdownCodeBlock = { fg = colors.red, bg = colors.backgroundDarkest },
		markdownCodeDelimiter = { fg = colors.orange },
		markdownH1 = { fg = colors.purpleDarkest, bold = true },
		markdownH2 = { fg = colors.purpleDarkest, bold = true },
		markdownH3 = { fg = colors.purpleDarkest, bold = true },
		markdownH4 = { fg = colors.purpleDarkest, bold = true },
		markdownH5 = { fg = colors.purpleDarkest, bold = true },
		markdownH6 = { fg = colors.purpleDarkest, bold = true },
		markdownHeadingDelimiter = { fg = colors.red },
		markdownHeadingRule = { fg = colors.textFaded },
		markdownId = { fg = colors.violet },
		markdownIdDeclaration = { fg = colors.blue },
		markdownIdDelimiter = { fg = colors.violet },
		markdownItalic = { fg = colors.yellow, italic = true },
		markdownLinkDelimiter = { fg = colors.violet },
		markdownLinkText = { fg = colors.blue },
		markdownListMarker = { fg = colors.blue },
		markdownOrderedListMarker = { fg = colors.purpleDefault },
		markdownRule = { fg = colors.textFaded },

		--  Diff
		diffAdded = { fg = colors.orange },
		diffRemoved = { fg = colors.red },
		diffFileId = { fg = colors.yellow, bold = true, reverse = true },
		diffFile = { link = "NonText" },
		diffNewFile = { fg = colors.orange },
		diffOldFile = { fg = colors.red },

		debugPc = { bg = colors.background },
		debugBreakpoint = { fg = colors.red, reverse = true },

		-- Git Signs
		GitSignsAdd = { fg = colors.green },
		GitSignsChange = { fg = colors.yellow },
		GitSignsDelete = { fg = colors.red },
		GitSignsAddLn = { link = "GitSignsAdd" },
		GitSignsChangeLn = { link = "GitSignsChange" },
		GitSignsDeleteLn = { link = "GitSignsChange" },
		GitSignsCurrentLineBlame = { fg = colors.purpleDefault },

		-- NvimTree
		NvimTreeNormal = { link = "Normal" },
		NvimTreeVertSplit = { fg = colors.background, bg = colors.background },
		NvimTreeRootFolder = { fg = colors.purpleDefault, bold = false },
		NvimTreeGitDirty = { fg = colors.yellow },
		NvimTreeGitNew = { link = "Number" },
		NvimTreeImageFile = { fg = colors.blue },
		NvimTreeFolderIcon = { fg = colors.violet },
		NvimTreeIndentMarker = { link = "NonText" },
		NvimTreeEmptyFolderName = { fg = colors.textFaded },
		NvimTreeFolderName = { fg = colors.purpleDefault },
		NvimTreeSpecialFile = { fg = colors.blue, underline = true },
		NvimTreeOpenedFolderName = { fg = colors.purpleDefault },
		NvimTreeCursorLine = { bg = colors.purpleLight },
		NvimTreeIn = { bg = colors.purpleLight },

		-- LSP
		DiagnosticError = { fg = colors.textDark, bg = colors.red },
		DiagnosticWarn = { fg = colors.textDark, bg = colors.yellow },
		DiagnosticInfo = { fg = colors.textDark, bg = colors.blue },
		DiagnosticHint = { fg = colors.textDark, bg = colors.blue },
		DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
		DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
		DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue },
		DiagnosticUnderlineHint = { undercurl = true, sp = colors.blue },
		DiagnosticSignError = { fg = colors.red },
		DiagnosticSignWarn = { fg = colors.yellow },
		DiagnosticSignInfo = { fg = colors.blue },
		DiagnosticSignHint = { fg = colors.blue },
		DiagnosticFloatingError = { fg = colors.red },
		DiagnosticFloatingWarn = { fg = colors.yellow },
		DiagnosticFloatingInfo = { fg = colors.blue },
		DiagnosticFloatingHint = { fg = colors.blue },
		DiagnosticVirtualTextError = { fg = colors.red },
		DiagnosticVirtualTextWarn = { fg = colors.yellow },
		DiagnosticVirtualTextInfo = { fg = colors.blue },
		DiagnosticVirtualTextHint = { fg = colors.blue },

		LspDiagnosticsDefaultError = { fg = colors.red },
		LspDiagnosticsDefaultWarning = { fg = colors.yellow },
		LspDiagnosticsDefaultInformation = { fg = colors.blue },
		LspDiagnosticsDefaultHint = { fg = colors.blue },
		LspDiagnosticsUnderlineError = { fg = colors.red, undercurl = true },
		LspDiagnosticsUnderlineWarning = { fg = colors.yellow, undercurl = true },
		LspDiagnosticsUnderlineInformation = { fg = colors.blue, undercurl = true },
		LspDiagnosticsUnderlineHint = { fg = colors.blue, undercurl = true },
		LspReferenceText = { fg = colors.yellow, bg = colors.purpleLight },
		LspReferenceRead = { fg = colors.yellow, bg = colors.purpleLight },
		LspReferenceWrite = { fg = colors.yellow, bg = colors.purpleLight },
		LspCodeLens = { fg = colors.blue },

		-- Cmp
		CmpItemAbbr = { fg = colors.white, bg = colors.background },
		CmpItemKind = { fg = colors.white, bg = colors.background },
		CmpItemKindMethod = { link = "@method" },
		CmpItemKindText = { link = "@text" },
		CmpItemKindFunction = { link = "@function" },
		CmpItemKindConstructor = { link = "@type" },
		CmpItemKindVariable = { link = "@variable" },
		CmpItemKindClass = { link = "@type" },
		CmpItemKindInterface = { link = "@type" },
		CmpItemKindModule = { link = "@namespace" },
		CmpItemKindProperty = { link = "@property" },
		CmpItemKindOperator = { link = "@operator" },
		CmpItemKindReference = { link = "@parameter.reference" },
		CmpItemKindUnit = { link = "@field" },
		CmpItemKindValue = { link = "@field" },
		CmpItemKindField = { link = "@field" },
		CmpItemKindEnum = { link = "@field" },
		CmpItemKindKeyword = { link = "@keyword" },
		CmpItemKindSnippet = { link = "@text" },
		CmpItemKindEvent = { link = "@constant" },
		CmpItemKindEnumMember = { link = "@field" },
		CmpItemKindConstant = { link = "@constant" },
		CmpItemKindStruct = { link = "@structure" },
		CmpItemKindTypeParameter = { link = "@parameter" },

		-- WinPicker
		-- WinPicker = { fg = colors.background, bg = colors.number },
	}
end

return M
